/**
 * CloudWatch Structured Metrics Logger
 *
 * Provides structured JSON logging for critical KavachPay events.
 * AgentCore observability dimensions (like policy ARN, enforcement mode)
 * will be generated by the Bedrock AgentCore system. This logger provides
 * the KavachPay operational metrics for correlation.
 */

export type MetricName =
  | "AUTH_ALLOW"
  | "AUTH_DENY"
  | "AUTH_STEP_UP"
  | "RESERVATION_CREATED"
  | "RESERVATION_RELEASED"
  | "PAYMENT_CREATED"
  | "PAYMENT_EXECUTED"
  | "PAYMENT_FAILED"
  | "RECONCILIATION_SUCCESS"
  | "RECONCILIATION_RETRY"
  | "RECONCILIATION_FAILURE"
  | "GRANT_CREATED"
  | "GRANT_REVOKED"
  | "GRANT_EXPIRED"
  | "INVARIANT_CHECK"
  | "INVARIANT_VIOLATION";

export const metrics = {
  logEvent(metric: MetricName, payload: Record<string, any> = {}) {
    // In a real AWS environment, this would use AWS Embedded Metrics Format (EMF)
    // or just output structured JSON for CloudWatch Logs.
    const logEntry = {
      timestamp: new Date().toISOString(),
      metric,
      ...payload,
    };
    
    // Use different log levels for CloudWatch alarm filtering
    if (metric === "INVARIANT_VIOLATION" || metric === "PAYMENT_FAILED" || metric === "RECONCILIATION_FAILURE") {
      console.error(JSON.stringify(logEntry));
    } else {
      console.log(JSON.stringify(logEntry));
    }
  }
};
