export const mandateDemo = {
  intent: "Buy groceries for me this week.",
  category: "GROCERY",
  weeklyLimit: "₹4,000 / WEEK",
  stepUpAbove: "> ₹1,500",
  blockedCategory: "ALCOHOL",
  expires: "SUN 23:59",
  delegationDepth: 2,
  reference: "KP–1967–M",
} as const;

export const decisionsDemo = {
  allow: {
    id: "TX–1081",
    agent: "Grocery Agent",
    category: "GROCERY",
    amount: "₹1,249",
    decision: "APPROVED",
    mandateRef: "KP–1967–M",
  },
  stepUp: {
    id: "TX–1082",
    agent: "Travel Agent",
    category: "TRAVEL",
    amount: "₹4,900",
    decision: "STEP-UP REQUIRED",
    constraint: "THRESHOLD > ₹1,500",
    mandateRef: "KP–1967–M",
  },
  deny: {
    id: "TX–1083",
    agent: "Shopping Agent",
    category: "BLOCKED MERCHANT",
    amount: "₹799",
    decision: "DENIED",
    constraint: "MANDATE RESTRICTION",
    mandateRef: "KP–1967–M",
  },
} as const;

export const delegationDemo = {
  parent: {
    id: "AUTH–0301",
    category: "SHOPPING",
    totalLimit: "₹4,000",
    weeklyLimit: "₹4,000 / WEEK",
    reference: "KP–1967–M",
    depthRule: "2 LEVELS MAX",
  },
  grocery: {
    id: "AUTH–0302",
    category: "GROCERY",
    amount: "₹1,500 / WEEK",
    derivedFrom: "SHOPPING (AUTH–0301)",
    level: 1,
    levelLabel: "LEVEL 1 OF 2",
    remainingLabel: "1 LEVEL REMAINING",
  },
  delivery: {
    id: "AUTH–0303",
    category: "DELIVERY",
    amount: "₹1,000 / WEEK",
    derivedFrom: "SHOPPING (AUTH–0301)",
    level: 1,
    levelLabel: "LEVEL 1 OF 2",
    remainingLabel: "1 LEVEL REMAINING",
  },
  downstreamDemo: {
    id: "AUTH–0304",
    category: "SECONDARY AUTHORITY",
    level: 2,
    levelLabel: "LEVEL 2 OF 2",
    remainingLabel: "NO FURTHER DELEGATION",
    derivedFrom: "GROCERY (AUTH–0302)",
    sealedReason: "2 LEVELS MAX",
  },
} as const;

export const stepUpDemo = {
  request: {
    id: "TX–1082",
    agent: "TRAVEL AGENT",
    category: "TRAVEL",
    amount: "₹4,900",
    reference: "AUTH–REQ–0401",
    mandateRef: "KP–1967–M",
    route: "AIRLINE // BOM → DEL",
  },
  clearance: {
    title: "TRAVEL AUTHORIZATION REQUEST",
    automaticLimit: "AUTOMATIC LIMIT ₹3,000",
    requestedAuthority: "REQUESTED AUTHORITY ₹4,900",
    autoClearanceLimit: "AUTO-CLEARANCE LIMIT ₹3,000",
    excessAmount: "EXCESS OVER LIMIT ₹1,900",
    holdStamp: "HOLD FOR CLEARANCE",
    referralNotice: "REFER FOR APPROVAL",
    actionClearOnce: "CLEAR ONCE",
    actionDecline: "DECLINE",
    clearanceScope: "SINGLE EXECUTION ONLY // APPLIES TO TX–1082 (₹4,900)",
    authToken: "AUTH–CLR–9941",
    microcopy: "HIGHER INTENT. HUMAN CLEARANCE.",
    footerTagline: "SAME MONEY. A SAFER TOMORROW.",
  },
} as const;

export const revocationDemo = {
  header: {
    index: "05",
    title: "REVOCATION",
    microcopy: "LINEAGE-AWARE REVOCATION. INDEPENDENT TRAVEL UNAFFECTED.",
  },
  source: {
    id: "AUTH-0301",
    agent: "SHOPPING AGENT",
    category: "SHOPPING",
    limit: "₹4,000 / WEEK",
    mandateRef: "KP–1967–M",
    role: "SOURCE AUTHORITY",
    statusInitial: "IN FORCE",
    statusRevoked: "REVOKED",
    recallAperture: "AUTHORITY RECALL APERTURE // DATUM 05",
    recallAction: "RECALL: SHOPPING AGENT",
    serialKey: "REG-SPINE-AUTH-0301-ROOT",
  },
  dependents: {
    grocery: {
      id: "AUTH-0302",
      agent: "GROCERY AGENT",
      category: "GROCERY",
      limit: "₹1,500 / WEEK",
      derivedFrom: "SHOPPING (AUTH-0301)",
      role: "DERIVED AUTHORITY // SIBLING A",
      statusInitial: "IN FORCE",
      statusWithdrawn: "AUTHORITY WITHDRAWN",
      serialKey: "REG-INHERIT-0301-A",
    },
    delivery: {
      id: "AUTH-0303",
      agent: "DELIVERY AGENT",
      category: "DELIVERY",
      limit: "₹1,000 / WEEK",
      derivedFrom: "SHOPPING (AUTH-0301)",
      role: "DERIVED AUTHORITY // SIBLING B",
      statusInitial: "IN FORCE",
      statusWithdrawn: "AUTHORITY WITHDRAWN",
      serialKey: "REG-INHERIT-0301-B",
    },
  },
  control: {
    reference: "TX-1082",
    requestRef: "AUTH-REQ-0401",
    agent: "TRAVEL AGENT",
    category: "TRAVEL",
    amount: "₹4,900",
    mandateRef: "KP–1967–M",
    role: "INDEPENDENT AUTHORITY // CONTROL CASE",
    status: "UNAFFECTED // ACTIVE",
    serialKey: "REG-INDEP-TX-1082-ACTIVE",
    note: "SEPARATE AUTHORITY LINEAGE — CONTINUES UNTOUCHED",
  },
  footer: {
    code: "REVOCATION // 05",
    tagline: "LINEAGE-AWARE CONTROL. PRESERVED PROVENANCE.",
  },
} as const;

export const splitDefenseDemo = {
  header: {
    index: "06",
    title: "SPLIT-PAYMENT DEFENSE",
    microcopy: "DIFFERENT TIMES. SAME INTENT.",
  },
  mandateRef: "KP–1967–M",
  threshold: "STEP-UP > ₹1,500",
  window: {
    id: "TW-2026-0917-A",
    label: "TEMPORAL CORRELATION APERTURE // 10:00–10:15",
    span: "6 MIN SPAN // 3 SATELLITE EVENTS",
  },
  requests: [
    {
      id: "TX-1091",
      amount: "₹1,000",
      numericAmount: 1000,
      time: "10:03",
      merchant: "MARKET MART",
      location: "MUMBAI",
      agent: "VIA AGENT ZEPTO",
      purpose: "PURPOSE GROCERY",
      status: "SUB-THRESHOLD // ₹1,000 < ₹1,500",
      serial: "SLIP-091-1003",
    },
    {
      id: "TX-1092",
      amount: "₹1,000",
      numericAmount: 1000,
      time: "10:06",
      merchant: "MARKET MART",
      location: "MUMBAI",
      agent: "VIA AGENT ZEPTO",
      purpose: "PURPOSE GROCERY",
      status: "SUB-THRESHOLD // ₹1,000 < ₹1,500",
      serial: "SLIP-092-1006",
    },
    {
      id: "TX-1093",
      amount: "₹1,000",
      numericAmount: 1000,
      time: "10:09",
      merchant: "MARKET MART",
      location: "MUMBAI",
      agent: "VIA AGENT ZEPTO",
      purpose: "PURPOSE GROCERY",
      status: "SUB-THRESHOLD // ₹1,000 < ₹1,500",
      serial: "SLIP-093-1009",
    },
  ],
  evidence: {
    merchant: "SAME MERCHANT.",
    agent: "SAME AGENT.",
    purpose: "SAME PURPOSE.",
    verdict: "IDENTICAL ORIGIN & CONTEXT DETECTED",
  },
  aggregation: {
    formula: "₹1,000 + ₹1,000 + ₹1,000",
    total: "₹3,000",
    thresholdComp: "AGGREGATE ₹3,000 > THRESHOLD ₹1,500",
    action: "ONE ECONOMIC ACTION",
    enforcement: "BLOCKED",
    auditNote: "MANDATE KP-1967-M INTACT // EVASION ATTEMPT CONTAINED",
  },
  stamps: {
    primary: "ONE ECONOMIC ACTION",
    secondary: "BLOCKED",
  },
  footer: {
    code: "SPLIT DEFENSE // 06",
    tagline: "TEMPORAL CORRELATION. BOUNDED INTENT.",
  },
} as const;

export const concurrencyDemo = {
  header: {
    index: "07",
    title: "BUDGET / CONCURRENCY",
    microcopy: "ONE BUDGET. ONE AT A TIME.",
  },
  mandateRef: "KP–1967–M",
  initialRemaining: "₹500",
  initialNumeric: 500,
  finalRemaining: "₹0",
  finalNumeric: 0,
  leftRequest: {
    id: "TX-1094",
    amount: "₹500",
    numericAmount: 500,
    merchant: "BLUE TOKAI CAFE",
    purpose: "CAFE",
    agent: "CONCIERGE AGENT",
    time: "10:14:02.110",
    serial: "SLIP-094-1014",
    statusInitial: "PENDING CLAIM",
    statusReserved: "RESERVED",
    statusCommitted: "COMMITTED",
    outcome: "COMMITTED",
  },
  rightRequest: {
    id: "TX-1095",
    amount: "₹500",
    numericAmount: 500,
    merchant: "STRAND BOOK STALL",
    purpose: "BOOKS",
    agent: "RESEARCH AGENT",
    time: "10:14:02.114",
    serial: "SLIP-095-1014",
    statusInitial: "PENDING CLAIM",
    statusReevaluated: "CONFRONTING CURRENT STATE",
    statusUnavailable: "UNAVAILABLE // ₹0 REMAINING",
    outcome: "UNAVAILABLE",
  },
  datum: {
    label: "COMMIT DATUM // ATOMIC SERIALIZATION",
    aperture: "RESERVATION APERTURE",
    preCommitStatus: "AVAILABLE: ₹500",
    postReservationStatus: "RESERVED: ₹500 // CURRENT: ₹0",
  },
  stamps: {
    reserved: "RESERVED",
    unavailable: "UNAVAILABLE",
  },
  accounting: {
    mandateCap: "₹4,000",
    mandateCapNumeric: 4000,
    priorSpend: "₹3,500",
    priorSpendNumeric: 3500,
    initialAvailable: "₹500",
    initialAvailableNumeric: 500,
    currentReservation: "₹500",
    currentReservationNumeric: 500,
    currentRemaining: "₹0",
    currentRemainingNumeric: 0,
    unfulfilledClaim: "₹500",
    unfulfilledClaimNumeric: 500,
    conservationProof: "₹3,500 PRIOR + ₹500 RESERVED + ₹0 REMAINING = ₹4,000",
  },
  footer: {
    code: "CONCURRENCY // 07",
    tagline: "ONE BUDGET. ONE AT A TIME.",
  },
} as const;

export const causalReplayDemo = {
  header: {
    index: "08",
    title: "CAUSAL REPLAY",
    microcopy: "AN OUTCOME IS NEVER A BLACK BOX.",
  },
  mandateRef: "KP–1967–M",
  subject: {
    id: "TX–1081",
    merchant: "BLINKIT",
    purpose: "GROCERY",
    amount: "₹1,249",
    agent: "Grocery Agent",
    time: "12:04:21.190",
    outcome: "COMMITTED",
  },
  layers: [
    {
      key: "provider",
      index: "08.01",
      label: "PROVIDER RESULT",
      question: "WHAT CAME BACK FROM EXTERNAL RAILS?",
      badge: "VERIFIED // RAZORPAY SANDBOX",
      fields: [
        { k: "DECISION RECEIPT", v: "RCP-1081-ALLOW" },
        { k: "WEBHOOK EVENT ID", v: "WHK-1081-A" },
        { k: "STATUS", v: "SUCCESS // COMMITTED" },
        { k: "SETTLED AMOUNT", v: "₹1,249" },
        { k: "TIMESTAMP", v: "12:04:21.190" },
        { k: "MODE", v: "PSP SANDBOX // TEST MODE" },
      ],
    },
    {
      key: "execution",
      index: "08.02",
      label: "EXECUTION",
      question: "WHAT DID KAVACHPAY DISPATCH TO THE PSP?",
      badge: "DISPATCHED",
      fields: [
        { k: "PROVIDER REQUEST ID", v: "REQ-1081-01" },
        { k: "REFERENCE TRANSACTION", v: "TX–1081" },
        { k: "MERCHANT", v: "BLINKIT // QUICK COMMERCE" },
        { k: "AUTHORISED AMOUNT", v: "₹1,249" },
        { k: "PSP ADAPTER", v: "RAZORPAY TEST ADAPTER" },
      ],
    },
    {
      key: "decision",
      index: "08.03",
      label: "DECISION",
      question: "WHAT DID KAVACHPAY'S POLICY ENGINE DECIDE?",
      badge: "APPROVED",
      fields: [
        { k: "EVALUATION RESULT", v: "APPROVED // ALLOW" },
        { k: "POLICY ENGINE", v: "AGENTCORE / CEDAR POLICY" },
        { k: "CATEGORY VERIFICATION", v: "GROCERY [PASS]" },
        { k: "STEP-UP RULE", v: "₹1,249 <= ₹1,500 THRESHOLD [PASS]" },
        { k: "AUTHORITY BASIS", v: "WITHIN MANDATE. WITHIN AUTHORITY. WITHIN BUDGET." },
      ],
    },
    {
      key: "budget",
      index: "08.04",
      label: "BUDGET STATE",
      question: "WHAT WAS THE HISTORICAL MONETARY STATE AT DECISION TIME?",
      badge: "HISTORICAL LEDGER PROOF",
      temporal: {
        before: [
          { k: "MANDATE CAP", v: "₹4,000" },
          { k: "PRIOR CUMULATIVE SPEND", v: "₹0" },
          { k: "AVAILABLE BEFORE", v: "₹4,000" },
        ],
        event: [
          { k: "TX–1081 ATOMIC RESERVATION", v: "₹1,249" },
        ],
        after: [
          { k: "COMMITTED RESERVATION", v: "₹1,249" },
          { k: "RESIDUAL CAPACITY REMAINING", v: "₹2,751" },
        ],
        proof: "₹0 PRIOR + ₹1,249 RESERVED + ₹2,751 REMAINING = ₹4,000 [VERIFIED // 100% INTACT]",
      },
      fields: [
        { k: "MANDATE CAP", v: "₹4,000" },
        { k: "AVAILABLE BEFORE", v: "₹4,000" },
        { k: "ATOMIC RESERVATION", v: "₹1,249" },
        { k: "REMAINING AFTER", v: "₹2,751" },
      ],
      proof: "₹0 PRIOR + ₹1,249 RESERVED + ₹2,751 REMAINING = ₹4,000 [VERIFIED // 100% INTACT]",
    },
    {
      key: "agentPath",
      index: "08.05",
      label: "AGENT PATH",
      question: "WHO ACTUALLY ATTEMPTED THE FINANCIAL ACTION?",
      badge: "CALLER IDENTITY",
      fields: [
        { k: "ACTING AGENT", v: "Grocery Agent" },
        { k: "CALLER PROVENANCE", v: "SHOPPING (AUTH–0301) → GROCERY (AUTH–0302)" },
        { k: "SUB-DELEGATION", v: "NONE ISSUED // TERMINAL LEAF" },
        { k: "AGENT CONTRACT", v: "BOUND TO GROCERY SCOPE" },
      ],
    },
    {
      key: "authority",
      index: "08.06",
      label: "AUTHORITY / DELEGATION",
      question: "WHO HAD THE RIGHT TO ACT?",
      badge: "DERIVED AUTHORITY",
      fields: [
        { k: "AUTHORITY GRANT", v: "AUTH–0302" },
        { k: "CATEGORY SCOPE", v: "GROCERY" },
        { k: "MAX SPEND CAP", v: "₹1,500 / WEEK" },
        { k: "DERIVED FROM", v: "SHOPPING AUTHORITY (AUTH–0301)" },
        { k: "DELEGATION DEPTH", v: "LEVEL 1 OF 2 [1 REMAINING]" },
      ],
    },
    {
      key: "mandate",
      index: "08.07",
      label: "MANDATE",
      question: "WHAT RULES GOVERNED THE ROOT FINANCIAL AUTHORITY?",
      badge: "INTENT CONTRACT",
      fields: [
        { k: "MANDATE REFERENCE", v: "KP–1967–M" },
        { k: "WEEKLY LIMIT", v: "₹4,000 / WEEK" },
        { k: "STEP-UP THRESHOLD", v: "> ₹1,500" },
        { k: "ALLOWED CATEGORIES", v: "GROCERY" },
        { k: "BLOCKED CATEGORIES", v: "ALCOHOL" },
        { k: "EXPIRY", v: "SUN 23:59" },
      ],
    },
    {
      key: "intent",
      index: "08.08",
      label: "ORIGINAL INTENT",
      question: "WHERE DID THE INSTRUCTION ORIGINATE?",
      badge: "ROOT HUMAN ORIGIN",
      fields: [
        { k: "ROOT PRINCIPAL", v: "HUMAN OWNER (YOU)" },
        { k: "NATURAL LANGUAGE PROMPT", v: "“Buy groceries for me this week.”" },
        { k: "COMPILATION TYPE", v: "DETERMINISTIC FINANCIAL INTENT CONTRACT" },
        { k: "AMPLIFICATION CHECK", v: "ZERO ADDITIVE CAPACITY MINTED" },
        { k: "PROVENANCE PROOF", v: "100% AUDITABLE LINEAGE TO HUMAN ROOT" },
      ],
    },
  ],
  footer: {
    code: "CAUSAL REPLAY // 08",
    tagline: "THE MONEY, RECONSTRUCTED.",
  },
} as const;

export type { ExperienceScene } from "./scene-registry";

